#!/usr/bin/env php
<?php
/*
 *       _____   _          __  _____   _____   _       _____   _____
 *     /  _  \ | |        / / /  _  \ |  _  \ | |     /  _  \ /  ___|
 *     | | | | | |  __   / /  | | | | | |_| | | |     | | | | | |
 *     | | | | | | /  | / /   | | | | |  _  { | |     | | | | | |   _
 *     | |_| | | |/   |/ /    | |_| | | |_| | | |___  | |_| | | |_| |
 *     \_____/ |___/|___/     \_____/ |_____/ |_____| \_____/ \_____/
 *
 * Copyright (c) 2023 by OwOTeam-DGMT (OwOBlog).
 * @Author       : HanskiJay
 * @Date         : 2023-02-14 18:01:56
 * @LastEditors  : HanskiJay
 * @LastEditTime : 2023-02-20 21:40:43
 * @E-Mail       : support@owoblog.com
 * @Telegram     : https://t.me/HanskiJay
 * @GitHub       : https://github.com/Tommy131
 */
declare(strict_types=1);



require_once(__DIR__ . '/src/script/bootstrap.php');
require_once(__DIR__ . '/src/script/systemFunctions.php');
require_once(__DIR__ . '/src/script/httpFunctions.php');

use owoframe\System;
use owoframe\console\Console;

System::init();
System::initializeApplications();
Console::getInstance()->init()->monitor($argv);